pipeline {
    agent {label:'cm-linux'}

    environment {
        EMAIL_RECIPIENTS = 'adityasuryawanshi5451@gmail.com'
    }

    stages {
        stage('Install Prerequisites') {
            steps {
                sh 'curl -sL https://deb.nodesource.com/setup_18.x | bash - && sudo apt-get install -y nodejs'
                sh 'npm install axios'
            }
        }

        stage('Execute Script') {
            steps {
                sh 'node CreateRecords.js'
            }
        }

        stage('Send Build Logs via Email') {
            steps {
                mail to: "${EMAIL_RECIPIENTS}",
                     subject: "Jenkins Build: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                     body: "Build completed. Check details at ${env.BUILD_URL}",
                     attachLog: true
            }
        }
    }

    post {
        failure {
            mail to: "${EMAIL_RECIPIENTS}",
                 subject: "Jenkins Build Failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Build failed. Check details at ${env.BUILD_URL}",
                 attachLog: true
        }
    }
}